name: Publish to NPM
on:
    push:
        branches: ['main']
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Setup Node
              uses: actions/setup-node@v3.9.1
              with:
                  node-version: '22.x'
                  registry-url: 'https://registry.npmjs.org'
            - name: Publish package on NPM 📦
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
